# ------ General Packages ------ #
[owo-sh]
src.git = "https://owo.codes/whats-this/owo.sh.git"
fetch.git = "https://owo.codes/whats-this/owo.sh.git"

[wheelwizard]
src.github = "TeamWheelWizard/WheelWizard"
fetch.git = "https://github.com/TeamWheelWizard/WheelWizard.git"


# ------ Linux-specific ------ #
[gpu-screen-recorder-ui]
src.git = "https://repo.dec05eba.com/gpu-screen-recorder-ui"
fetch.git = "https://repo.dec05eba.com/gpu-screen-recorder-ui"
git.fetchSubmodules = true

[gpu-screen-recorder-notification]
src.git = "https://repo.dec05eba.com/gpu-screen-recorder-notification"
fetch.git = "https://repo.dec05eba.com/gpu-screen-recorder-notification"
git.fetchSubmodules = true

[helium-tarball]
src.github = "imputnet/helium-linux"
fetch.url = "https://github.com/imputnet/helium-linux/releases/download/$ver/helium-$ver-x86_64_linux.tar.xz"

[dzgui]
src.git = "https://codeberg.org/aclist/dztui"
fetch.git = "https://codeberg.org/aclist/dztui"


# ------ Darwin-specific ------ #
[swipeaerospace-bin]
src.github = "MediosZ/SwipeAeroSpace"
fetch.url = "https://github.com/MediosZ/SwipeAeroSpace/releases/download/$ver/SwipeAeroSpace.zip"

[helium-dmg]
src.github = "imputnet/helium-macos"
fetch.url = "https://github.com/imputnet/helium-macos/releases/download/$ver/helium_$ver_arm64-macos.dmg"

[pearcleaner-bin]
src.github = "alienator88/Pearcleaner"
fetch.url = "https://github.com/alienator88/Pearcleaner/releases/download/$ver/Pearcleaner.dmg"

[protonmail-bin]
src.webpage = "https://proton.me/download/mail/macos/version.json"
src.regex = '"Version":\s*"([0-9.]+)"'
fetch.url = "https://proton.me/download/mail/macos/$ver/ProtonMail-desktop.dmg"

[protonpass-bin]
src.webpage = "https://proton.me/download/PassDesktop/darwin/universal/version.json"
src.regex = '"Version":\s*"([0-9.]+)"'
fetch.url = "https://proton.me/download/PassDesktop/darwin/universal/ProtonPass_$ver.dmg"

[protonvpn-bin]
src.webpage = "https://protonvpn.com/download/macos/updates/v4/sparkle.xml"
src.regex = '<title>Version\s+((?!beta)\d+\.\d+\.\d+)</title>'
fetch.url = "https://vpn.protondownload.com/download/macos/$ver/ProtonVPN_mac_v$ver.dmg"

# ------ Non-program packages ------ #
[base16-schemes]
src.git = "https://github.com/tinted-theming/schemes.git"
fetch.git = "https://github.com/tinted-theming/schemes.git"

[apple-emoji]
src.github = "samuelngs/apple-emoji-linux"
fetch.url = "https://github.com/samuelngs/apple-emoji-linux/releases/download/$ver/AppleColorEmoji.ttf"

[liga-sf-mono-nerd-font]
src.git = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized.git"
fetch.git = "https://github.com/shaunsingh/SFMono-Nerd-Font-Ligaturized.git"
